export const betingelser = [
    {
        id: 1,
        name: 'Standard Betingelser',
        title: 'Standard Betingelser',
        heading1: 'ERPgruppen A/S',
        p1: 'ERPgruppen er en IT- og konsulentvirksomhed, der leverer support, rådgivning og IT-løsninger til ERP-programmerne Microsoft Dynamics 365 Business Central, Microsoft Dynamics NAV og Dynamics C5.',
        heading2: 'Anvendelse',
        p2: 'Følgende standardbetingelser gælder for samarbejdet mellem Køber og ERPgruppen, med mindre andet er aftalt skriftligt.',
        heading3: 'Fakturering og betaling',
        p3: 'Fakturering af faste månedlige omkostninger sker samlet ved opstart af Dynamics 365 Business Central og Dynamics 365 Sales. Fakturering af tilkøb sker hver mandag i lige uger, af foregående 14 dages leverancer, så Køber løbende er opdateret med de ydelser, vi har leveret. Faktureringen sker uanset om projektet er færdigt eller ej. Faktura vil blive sendt pr. mail til kunde med betalingsbetingelse otte dage netto. Ved udebleven betaling tilskrives renter af vores tilgodehavende med procesrente (Nationalbankens udlånsrente + 8% p.a.). Renter beregnes fra forfaldsdatoen. Renter og rykkergebyrer opkræves i henhold til gældende lovgivning. Fakturering af opdateringsabonnement for en ejet licens sker 75 dage forud for en periode á 12 måneder. Fakturering af øvrige abonnementer sker 30 dage forud for en periode á 12 måneder, medmindre andet er aftalt. Ved udebleven betaling i mere end 30 dage fra forfaldsdato, kan ERPgruppen lukke adgang til ERP-systemet. For at få genåbnet adgang til ERP-systemet eller få udlæst kundens data, opkræves et gebyr på kr. 1.500.',
        heading4: 'Priser',
        p4: '',
        heading5: 'Levering',
        p5: '',
        heading6: 'Varighed og opsigelse',
        p6: '',
        heading7: 'ERPgruppen ansvar',
        p7: '',
        heading8: 'Underleverandør/3. parts ansvar',
        p8: '',
        heading9: 'Tavshedspligt',
        p9: '',
        heading10: 'Databeskyttelse',
        p10: '',
        heading11: 'Force Majeure',
        p11: '',
        heading12: 'Persondatapolitik',
        p12: '',
        heading13: 'Nyhedsbrev',
        p13: '',
        heading14: 'Tvister',
        p14: '',
    },
]

export const politik = [
    {
        id: 1,
        name: 'Data Politik',
        title: 'Data Politik',
        heading1: 'Brug af cookies på website',
        p1: 'På ERPgruppen A/S hjemmesider (ERPgruppen.dk, ERPsupporten.dk, Stackss.dk) indsamler vi statistik om vores besøgendes færden på siderne. For at kunne gøre dette er vi nødt til at lade din browser downloade en uskadelig cookie-fil. Dette sker automatisk, når du besøger hjemmesiderne, og det vil ikke påvirke din brugeroplevelse. Vi får informationer om, hvordan de besøgende endte på siden (fra Google), hvilken browser de bruger, hvilke sider de ser, om de downloader en PDF samt en række andre informationer. Dette gør vi for at kunne optimere hjemmesiderne og give dig som besøgende den bedste brugeroplevelse.Vi bruger ikke data til at spore enkeltpersoners færden på siden, men ser på et samlet gennemsnit af data, så du vil aldrig blive registreret individuelt. Som hovedregel hjælper cookies dig til en bedre oplevelse af de sider, du benytter. Vi anbefaler derfor, at du tillader brug af cookies på dette site. Hvis du er indforstået med det, skal du ikke foretage dig yderligere. Ønsker du ikke at indgå i vores statistik, kan du slå cookies fra i dine browserindstillinger. Hvis du vælger at slå cookies fra på denne og/eller andre sider, så er den mest effektive og sikre måde at gøre det på direkte i din browser. Kik under “Hjælp” i din browser.',
        heading2: 'Privatpolitik',
        p2: 'Vi har stort fokus på, at vores indsamling, behandling og brug af persondata stemmer overens med gældende regler for persondataforordningen. På hjemmesiderne indsamler vi brugeroplysninger via forskellige kontaktformularer, som den besøgende selv vælger at udfylde. De oplysninger, der spørges til, varierer alt efter, hvilken situation det drejer sig om. Det kan være almen kontakthenvendelse, hvor den besøgende ønsker at blive kontaktet af os. Vi bruger oplysningerne til at præcisere, hvem og hvordan vi kan kontakte vedkommende. E-mailadresse vil som udgangspunkt altid være obligatorisk at udfylde, hvorimod telefonnummer er valgfrit. Det kan også være ved tilmelding til event. Vi bruger oplysningerne til at præcisere firma og deltageren, herunder stilling, kontaktoplysninger og evt. IT-system. Det bruger vi til bedre at kunne målrette, hvem vi taler til i forbindelse med eventet. Ved tilmelding til eventet afkrydser deltageren desuden, hvorvidt vi må sende nyhedsbrev. Nyhedsbrevet kan til enhvert tid afmeldes. Det kan også være ved bestilling af et produkt eller ydelse (eks. supportaftale, kursus). Her kan der tilmeld spørges til oplysninger som firmaadresse og cvr.nummer. Disse oplysninger bruges til at validere og fakturere køberen. Det kan også være ved udfyldelse af spørgeundersøgelser. Vi bruger oplysningerne til at få indsigt i, hvem besvarelsen kommer fra for evt. at kunne følge op for nærmere uddybelse. Når der indsamles oplysninger via vores hjemmesider, sikrer vi, at det sker ved afgivelse af samtykke, så du er informeret om præcis, hvilke oplysninger, der er indsamlet og hvorfor. Oplysningerne opbevares på ubestemt tid med det formål at skabe historik og arkivere eventuel dialog og aftale. Du har til enhver tid ret til, jvf. persondataloven, at få indsigt i, hvilke oplysninger, der er registreret om dig. Du bedes rette henvendelse til mail@erpgruppen.dk.',
        heading3: 'Nyhedsbrev',
        p3: 'ERPgruppen er en moderkoncern, som udsender nyheder for ERPgruppen og vores tilhørende datterselskaber (ERPgruppen Kolding, ERPgruppen Horsens, ERPgruppen Aarhus, ERPgruppen Slagelse, ERPgruppen Padborg, ERPsupporten.dk og Stackss). Ved samtykke accepterer du, at ERPgruppen må sende dig elektronisk post (f.eks. e-mail) samt via sociale medier (LinkedIn, Facebook) og andre digitale kanaler vedrørende markedsføring, kampagner, konkurrencer og rådgivning. ERPgruppen må indsamle og bruge data om dig og dine aktiviteter og samkøre disse data med andre oplysninger, ERPgruppen allerede har eller får fra anden side, herunder f.eks. cookie fra ERPgruppens hjemmesider, for at kunne målrette henvendelser til dig. ERPgruppen må dele data om dig og dine aktiviteter internt og med koncernens datterselskaber og benytte disse informationer til at kontakte dig via elektronisk post og telefon. Oplysningerne bruger vi til bedre at kunne målrette vores nyhedsbrev til dig. Oplysninger videregives ikke til andre uden for ERPgruppen, uden du har givet samtykke hertil. Vi sender nyheder ud, der vedrører ERPgruppen og vores produktsortiment.',
    },
]