import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//components
import Hero from '../components/Hero'
import AboutHero from '../components/AboutHero'
import OurTeam from '../components/team/OurTeam'
import OurServices from '../components/services/OurServices'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <AboutHero />
      <OurTeam />
      <OurServices />
      
       
      </main>

    </div>
  )
}
