import Head from "next/head";
import { useState } from 'react'

//components
import Navigation from '../components/Navigation'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { betingelser } from '../components/policy/Policy'
import PolicyTemplate from '../components/policy/PolicyTemplate'

export default function Purchase() {

  const [ toggleMenu, setToggleMenu ] = useState(false)

  return (
    <div>
      <Head>
        <title>Betingelser | ERPGRUPPEN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="erp gruppen, betingelser" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <html lang="da" />
        <link rel="icon" href="/favicon.ico" />
         <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
      <Header toggleMenu={toggleMenu} setToggleMenu={setToggleMenu} />
      <Navigation toggleMenu={toggleMenu} setToggleMenu={setToggleMenu} />
      {betingelser.map((props) => {
        return (
          <PolicyTemplate
            key={props.id}
            id={props.id}
            name={props.name}
            heading1={props.heading1}
            p1={props.p1}
            heading2={props.heading2}
            p2={props.p2}
            heading3={props.heading3}
            p3={props.p3}
            heading4={props.heading4}
            p4={props.p4}
            heading5={props.heading5}
            p5={props.p5}
            heading6={props.heading6}
            p6={props.p6}
            heading7={props.heading7}
            p7={props.p7}
            heading8={props.heading8}
            p8={props.p8}
            heading9={props.heading9}
            p9={props.p9}
            heading10={props.heading10}
            p10={props.p10}
            heading11={props.heading11}
            p11={props.p11}
            heading12={props.heading12}
            p12={props.p12}
            heading13={props.heading13}
            p13={props.p13}
            heading14={props.heading14}
            p14={props.p14}
          />
        )
      })}
        <Footer />
      </main>
    </div>
  );
}
