import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { OpenOutline } from "react-ionicons";
import { Users, Cabola, Apple } from "../components/case/Users";
import Info from "../components/case/Info";

//components
import Navigation from "../components/Navigation";
import Header from "../components/Header";
import Modal from "../components/modals/Modal";

const caseOne = [
  {
    id: 1,
    name: "Cabola ApS",
    title: "Dynamics 365 Business Central",
    textBox1:
      "Cabola er en virksomhed der blev stiftet i 2004 og drives af direktør Kenneth Laursen. Kemieksperterne i Cabola tilbyder alle former for kemi; kemiske produkter, rengøringsmilder, saltprodukter og filtermaterialer. Med et stærkt team af ni medarbejdere knokler de dagligt for at sikre deres kunder den bedste løsning.",
    textBox2:
      "Mange virksomheder udelukker muligheden for nyt ERP-system fordi det er omkostningsdyrt, men for Cabola har beslutningen være en investering fordi det er et simpelt system der nemt kan integreres med andre systemer som virksomheden dagligt bruger. Cabola har fået implementeret Nemhandel som også er et af ERP-gruppens tillægsløsninger.",
    textBox3:
      "Takket være ERP-løsningen og den gode support fra ERPsupportens konsulenter så har Cabola opnået en øget effektivitet i arbejdsdagen.  Cabola medarbejderne kan selv arbejde i systemet og får rigtig god support af konsulenterne som altid er til rådighed og vejleder i systemet. De nye opdateringer der kommer, kan mærkes hos Cabola,  som er velinformeret omkring dette af ERPsupportens Konsulenter.",
    href: "case",
    imageSrc:
      "https://images.unsplash.com/photo-1561654791-00316c79efa8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8",
    imageAlt: "caseOne",
    price: "caseOne",
    color: "caseOne",
  },
];

function Case() {
  const [toggleMenu, setToggleMenu] = useState(false);

  const [open, setOpen] = useState(false);

  return (
    <div>
      <Head>
        <title>ERP PRODUKTION</title>
        <meta name="description" content="Generated by create next app" />
        <html lang="da" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Header toggleMenu={toggleMenu} setToggleMenu={setToggleMenu} />
      <Navigation toggleMenu={toggleMenu} setToggleMenu={setToggleMenu} />
      {Cabola.map((e) => {
        return (
          <Info
            id={e.id}
            name={e.name}
            title={e.title}
            textBox1={e.textBox1}
            textBox2={e.textBox2}
            textBox3={e.textBox3}
            href={e.href}
            imageSrc={e.imageSrc}
            imageAlt={e.imageAlt}
          />
        );
      })}
    </div>
  );
}

export default Case;
