import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

//components
import Navigation from "../components/Navigation";
import Header from "../components/Header";
import Modal from "../components/modals/Modal";

const caseOne = [
  {
    id: 1,
    name: "Cabola ApS",
    title: "Dynamics 365 Business Central",
    textBox1:
      "Cabola er en virksomhed der blev stiftet i 2004 og drives af direktør Kenneth Laursen. Kemieksperterne i Cabola tilbyder alle former for kemi; kemiske produkter, rengøringsmilder, saltprodukter og filtermaterialer. Med et stærkt team af ni medarbejdere knokler de dagligt for at sikre deres kunder den bedste løsning.",
    textBox2:
      "Mange virksomheder udelukker muligheden for nyt ERP-system fordi det er omkostningsdyrt, men for Cabola har beslutningen være en investering fordi det er et simpelt system der nemt kan integreres med andre systemer som virksomheden dagligt bruger. Cabola har fået implementeret Nemhandel som også er et af ERP-gruppens tillægsløsninger.",
    textBox3:
      "Takket være ERP-løsningen og den gode support fra ERPsupportens konsulenter så har Cabola opnået en øget effektivitet i arbejdsdagen.  Cabola medarbejderne kan selv arbejde i systemet og får rigtig god support af konsulenterne som altid er til rådighed og vejleder i systemet. De nye opdateringer der kommer, kan mærkes hos Cabola,  som er velinformeret omkring dette af ERPsupportens Konsulenter.",
    href: "case",
    imageSrc:
      "https://images.unsplash.com/photo-1561654791-00316c79efa8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8",
    imageAlt: "caseOne",
    price: "caseOne",
    color: "caseOne",
  },
];

function Case() {
  const [toggleMenu, setToggleMenu] = useState(false);

  const [open, setOpen] = useState(false);

  return (
    <div>
      <Head>
        <title>ERP PRODUKTION</title>
        <meta name="description" content="Generated by create next app" />
        <html lang="da" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Header toggleMenu={toggleMenu} setToggleMenu={setToggleMenu} />
      <Navigation toggleMenu={toggleMenu} setToggleMenu={setToggleMenu} />
      <div className="grid max-w-7xl mx-auto">
        {caseOne.map((product) => (
          <div key={product.id} className="group relative mt-20">
            <div className="md:flex">
              <div className="w-full min-h-80 aspect-w-1 p-5 aspect-h-1 overflow-hidden lg:h-full lg:aspect-none">
                <h3 className="text-5xl flex font-semibold">
                  {product.name}
                  <div className="flex ml-3">
                    <Modal open={open} setOpen={setOpen} />
                  </div>
                </h3>
                <span
                  aria-hidden="true"
                  className="text-gray-300 w-96 mt-5 text-4xl font-regular flex"
                >
                  {product.title}
                </span>
              </div>
              <div className="w-full min-h-80 aspect-w-1 aspect-h-1 overflow-hidden lg:h-full lg:aspect-none flex">
                <h3 className="font-regular m-5 text-lg">{product.textBox1}</h3>
              </div>
            </div>
            <img
              className="w-full h-1/3 object-center object-cover lg:w-full lg:h-1/4 mt-20"
              src={product.imageSrc}
              alt={product.imageAlt}
            />
            <div className="w-full aspect-w-1 aspect-h-1 overflow-hidden lg:h-full lg:aspect-none">
              <div className="flex mx-auto justify-center">
                <h3 className="m-12 text-md">
                  Strategy
                  <span className="flex text-sm m-3">Hello</span>
                  <span className="flex text-sm m-3">Hello</span>
                </h3>
                <h3 className="m-12 text-md">
                  User Experience
                  <span className="flex text-sm m-3">Hello</span>
                  <span className="flex text-sm m-3">Hello</span>
                </h3>
                <h3 className="m-12 text-md">
                  Production
                  <span className="flex text-sm m-3">Hello</span>
                  <span className="flex text-sm m-3">Hello</span>
                </h3>
                <h3 className="m-12 text-md">
                  Platforms
                  <span className="flex text-sm m-3">Hello</span>
                  <span className="flex text-sm m-3">Hello</span>
                </h3>
              </div>
              <div className="mt-20 mx-12">
                <h3 className="text-5xl flex font-semibold">
                  Nye implementeringer
                </h3>
                <h3 className="mt-8 font-regular text-lg gri">
                  {product.textBox2}
                  <span className="mt-5 flex">{product.textBox3}</span>
                </h3>
              </div>
              <div className="mt-20 1xl:mt-60 justify-center mx-12">
                <div className="flex invisible h-0 lgbasemd:h-auto lgbasemd:visible">
                  <img
                    className="h-16 w-auto pl-6"
                    src={
                      "https://res.cloudinary.com/ds8p0huok/image/upload/v1645175524/Ellipse_92_wpnmfl.png"
                    }
                    alt="mockup"
                  />
                  <div className="flex flex-col items-center justify-center pl-2">
                    <h2 className="font-bold">Niels pedersen</h2>
                    <p>CEO, Cabola ApS</p>
                  </div>
                </div>
                <div className="p-10 w-2/3 items-center justify-center invisible h-0 lgbasemd:h-auto lgbasemd:visible lgbasemd:space-x-6 smbaselg:space-x-16 aboutlg:space-x-20 baselg:space-x-28 base2lg:space-x-36">
                  <blockquote className="pt-1 pl-1">
                    &gt;{product.textBox3}
                  </blockquote>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Case;
