import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//components
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Hero />
      
       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/erp.svg" alt="ERP Produktion Logo" width={202} height={36} />
          </span>
        </a>
      </footer>
    </div>
  )
}
