import Head from "next/head";
import { useState } from 'react'

//components
import Navigation from '../components/Navigation'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { politik } from '../components/policy/Policy'
import PolicyTemplate from '../components/policy/PolicyTemplate'

export default function Trade() {

  const [ toggleMenu, setToggleMenu ] = useState(false)

  return (
    <div>
      <Head>
        <title>Policy | ERPGRUPPEN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="erp gruppen, policy" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <html lang="da" />
        <link rel="icon" href="/favicon.ico" />
         <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
      <Header toggleMenu={toggleMenu} setToggleMenu={setToggleMenu} />
      <Navigation toggleMenu={toggleMenu} setToggleMenu={setToggleMenu} />
      {politik.map((props) => {
        return (
          <PolicyTemplate
            key={props.id}
            id={props.id}
            name={props.name}
            heading1={props.heading1}
            p1={props.p1}
            heading2={props.heading2}
            p2={props.p2}
            heading3={props.heading3}
            p3={props.p3}
            text={props.text}
          />
        )
      })}
        <Footer />
      </main>
    </div>
  );
}
